# Generated by Django 5.1.1 on 2025-11-11 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100, verbose_name='測站名稱')),
                ('device_model', models.CharField(max_length=50, verbose_name='設備型號')),
                ('location', models.CharField(max_length=100, verbose_name='裝設地點')),
                ('install_date', models.DateField(verbose_name='裝設日期')),
            ],
            options={
                'verbose_name': '測站',
                'verbose_name_plural': '測站',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='時間戳')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='溫度')),
                ('conductivity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='電導率')),
                ('pressure', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='壓力')),
                ('oxygen', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='溶氧')),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='酸鹼值')),
                ('fluorescence', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='螢光值')),
                ('turbidity', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='濁度')),
                ('salinity', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='鹽度')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='data_ingestion.station', verbose_name='測站')),
            ],
            options={
                'verbose_name': '數據記錄',
                'verbose_name_plural': '數據記錄',
                'ordering': ['-timestamp'],
            },
        ),
    ]
