# Generated by Django 5.2.7 on 2025-12-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0002_station_latitude_station_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='reading',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='經度'),
        ),
    ]
