# Generated by Django 5.2.7 on 2025-12-19 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily_statistics', '每日統計報告'), ('data_update', '數據更新報告'), ('alert_check', '異常檢查報告'), ('custom', '自定義報告')], max_length=50, verbose_name='報告類型')),
                ('title', models.CharField(max_length=200, verbose_name='報告標題')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失敗'), ('warning', '警告')], default='success', max_length=20, verbose_name='狀態')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('content', models.JSONField(default=dict, verbose_name='報告內容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('task_id', models.CharField(blank=True, max_length=100, verbose_name='Celery 任務 ID')),
            ],
            options={
                'verbose_name': '報告',
                'verbose_name_plural': '報告',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='station_dat_created_e3023f_idx'), models.Index(fields=['report_type'], name='station_dat_report__251ffd_idx')],
            },
        ),
    ]
