# Generated by Django 5.2.7 on 2025-12-22 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0003_reading_latitude_reading_longitude'),
        ('station_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='data_ingestion.station', verbose_name='關聯測站'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('daily_statistics', '每日統計報告'), ('station_daily', '測站每日報告'), ('data_update', '數據更新報告'), ('alert_check', '異常檢查報告'), ('custom', '自定義報告')], max_length=50, verbose_name='報告類型'),
        ),
    ]
